// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.29 by WSRD Tencent.
// Generated from `../jce/src/test/test.jce'
// **********************************************************************

package Test
const (
    orange = 1
    apple = 2
)
